spring:
  application:
    name: resource-server-bookings
  jackson:
    serialization:
      indent_output: true

server:
  port: 9000

service:
  flights-api:
    service-name: flights-api
    service-address: http://localhost:9010/api/flights/v1

logging:
  level:
    pl.michalregulski: DEBUG
    org.springframework: INFO

security:
  oauth2:
    client:
      client-id: bookings
      client-secret: bookingssecret
    resource:
      user-info-uri: http://localhost:8080/auth/me
      token-info-uri: http://localhost:8080/auth/oauth/check_token
