spring:
  application:
    name: resource-server-flights
  jackson:
    serialization:
      indent_output: true

server:
  port: 9010

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/auth/user
      tokenInfoUri: http://localhost:8080/auth/oauth/check_token
    client:
      client-id: flights
      client-secret: flightssecret

logging:
  level:
    pl.michalregulski: DEBUG
    org.springframework: INFO
