spring:
  application:
    name: client
  jackson:
    serialization:
      indent_output: true

server:
  port: 8090

service:
  bookings-api:
    service-name: bookings-api
    service-address: http://localhost:9000/api/bookings/v1

logging:
  level:
    pl.michalregulski: DEBUG
    org.springframework: INFO

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://localhost:8080/auth/oauth/token
      user-authorization-uri: http://localhost:8080/auth/oauth/authorize
      scope: read-flights, read-bookings
    resource:
      user-info-uri: http://localhost:8080/auth/user
